name: agre_lens_app
description: "Agre Lens"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  intl: ^0.20.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  buildcondition: ^0.0.4
  dio: ^5.8.0+1
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  change_app_package_name: ^1.4.0
  flutter_datetime_picker_plus: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  